name: dartxx
version: 0.5.5-dev.0
description: A new Flutter package project.
repository: https://github.com:ericmartineau/dartxx
environment: 
  sdk: '>=2.16.0 <3.0.0'
dependencies: 
  equatable: ^2.0.3
  inflection3: ^0.5.3+2
  intl: ^0.17.0
  recase: ^4.0.0
dev_dependencies: 
  pedantic: ^1.11.1
  test: ^1.21.1
  test_api: ^0.4.9
