name: dartxx
version: 0.4.4+1
description: A new Flutter package project.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  recase: ^4.0.0-nullsafety.0
  inflection3: ^0.5.3+1
  intl: ^0.17.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: null
