name: dartxx
version: 0.5.0+1
description: A new Flutter package project.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  equatable: ^2.0.0
  inflection3: ^0.5.3+1
  intl: ^0.17.0
  recase: ^4.0.0-nullsafety.0
dev_dependencies: 
  test_api: ^0.3.0
  pedantic: ^1.11.0
  flutter_test: 
    sdk: flutter
dependency_overrides: 
  test_api: ^0.3.0
